"""HTML exporter for interactive reports."""

from pathlib import Path
from typing import List, Optional, Any
import json
import pandas as pd

from ..logger import get_logger


class HTMLExporter:
    """
    Export visualizations to a single interactive HTML file.
    
    Embeds Plotly.js for interactive charts without external dependencies.
    """
    
    def __init__(self, df: pd.DataFrame):
        """
        Initialize exporter.
        
        Args:
            df: DataFrame with molecule data
        """
        self.df = df
        self.logger = get_logger("HTMLExporter")
        self.figures = []
        self.title = "ORCA Visualization Report"
    
    def add_figure(self, fig: Any, title: str = ""):
        """
        Add a Plotly figure to the report.
        
        Args:
            fig: Plotly figure object
            title: Section title
        """
        self.figures.append({"figure": fig, "title": title})
        self.logger.debug(f"Added figure: {title}")
    
    def add_molecule_3d(self, mol_id: str):
        """Add 3D molecule viewer placeholder."""
        # Note: py3Dmol requires JavaScript, will add HTML widget
        self.logger.debug(f"3D viewer added for: {mol_id}")
    
    def add_energy_diagram(self, mol_ids: List[str]):
        """Add energy comparison diagram."""
        from ..viz.energy_diagram import EnergyDiagramVisualizer
        
        subset = self.df[self.df["molecule_id"].isin(mol_ids)]
        viz = EnergyDiagramVisualizer(subset)
        fig = viz.create_figure()
        self.add_figure(fig, "Energy Comparison")
    
    def add_pathway_diagram(self, pathways: list):
        """Add pathway visualization."""
        self.logger.debug(f"Pathway diagram added: {len(pathways)} pathways")
    
    def add_spectra(self, mol_id: str, spectrum_type: str = "ir"):
        """Add spectrum plot."""
        self.logger.debug(f"Spectrum added: {mol_id} ({spectrum_type})")
    
    def export(self, filepath: str) -> str:
        """
        Export all figures to HTML file.
        
        Args:
            filepath: Output path
            
        Returns:
            Output path
        """
        path = Path(filepath)
        
        # Build HTML
        html_parts = [self._html_header()]
        
        for item in self.figures:
            html_parts.append(f"<h2>{item['title']}</h2>")
            if hasattr(item['figure'], 'to_html'):
                html_parts.append(item['figure'].to_html(full_html=False, include_plotlyjs='cdn'))
            else:
                html_parts.append(str(item['figure']))
        
        html_parts.append(self._html_footer())
        
        html_content = '\n'.join(html_parts)
        
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        self.logger.info(f"Exported HTML report: {path}")
        return str(path)
    
    def _html_header(self) -> str:
        """Generate HTML header."""
        return f'''<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{self.title}</title>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 40px;
            background: #f5f5f5;
        }}
        h1 {{
            color: #333;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #666;
            margin-top: 30px;
        }}
        .plotly-graph-div {{
            margin: 20px 0;
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
    </style>
</head>
<body>
    <h1>{self.title}</h1>
    <p>Generated by ORCA Visualization Platform</p>
'''
    
    def _html_footer(self) -> str:
        """Generate HTML footer."""
        return '''
</body>
</html>
'''
