"""
Example: Molecular Electrostatic Potential (MEP) Analysis

Demonstrates how to parse and visualize MEP data from ORCA calculations.

MEP is critical for:
- Understanding charge distribution
- Identifying nucleophilic sites (negative MEP, electron-rich)
- Identifying electrophilic sites (positive MEP, electron-poor)
- Predicting degradation pathways
- Analyzing interaction sites

REQUIREMENTS:
To generate MEP data in ORCA, add to your input file:
    %plots
        dim1 100
        dim2 100
        dim3 100
        Format Gaussian_Cube
        ElPot("mep.cube");
    end

This generates a .cube file with MEP on a 3D grid.
"""

import sys
import os
import numpy as np

# Add parent directory to path for imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from parsers.mep_parser import MEPParser, MEPData
from visualization.mep_visualization import (
    create_mep_slice_plot,
    create_mep_multi_slice_plot,
    create_mep_3d_isosurface_plot,
    create_mep_critical_points_plot
)
import matplotlib.pyplot as plt


def example_parse_cube_file():
    """
    Example: Parse MEP from .cube file.

    The .cube file is generated by ORCA using:
        %plots ElPot("mep.cube"); end
    """
    print("=" * 80)
    print("MEP ANALYSIS FROM CUBE FILE")
    print("=" * 80)
    print()

    # File path (UPDATE THIS to your actual file path)
    cube_file = "path/to/mep.cube"

    if not os.path.exists(cube_file):
        print(f"ERROR: File not found: {cube_file}")
        print("\nPlease update the file path in this script.")
        print("\nTo generate MEP cube file in ORCA, add to input:")
        print("    %plots")
        print("        dim1 100")
        print("        dim2 100")
        print("        dim3 100")
        print("        Format Gaussian_Cube")
        print('        ElPot("mep.cube");')
        print("    end")
        return

    print(f"Parsing cube file: {cube_file}")
    mep_data = MEPParser.parse_cube_file(cube_file)

    # Print summary
    summary = MEPParser.print_summary(mep_data)
    print(summary)
    print()

    # Find critical points
    print("Finding critical points (reactive sites)...")
    mep_data.find_critical_points(threshold=0.01)
    print(f"  Found {len(mep_data.local_minima)} nucleophilic sites (MEP minima)")
    print(f"  Found {len(mep_data.local_maxima)} electrophilic sites (MEP maxima)")
    print()

    # Create visualizations
    print("Creating visualizations...")
    output_dir = "mep_analysis"
    os.makedirs(output_dir, exist_ok=True)

    # 1. Single slice through molecule
    fig1 = create_mep_slice_plot(
        mep_data,
        slice_axis='z',
        slice_position=None,  # Middle slice
        output_file=f"{output_dir}/mep_slice_z.png",
        show_atoms=True
    )
    print(f"  Saved: {output_dir}/mep_slice_z.png")

    # 2. Multiple slices
    fig2 = create_mep_multi_slice_plot(
        mep_data,
        axis='z',
        n_slices=6,
        output_file=f"{output_dir}/mep_multi_slice.png"
    )
    print(f"  Saved: {output_dir}/mep_multi_slice.png")

    # 3. 3D isosurface visualization
    fig3 = create_mep_3d_isosurface_plot(
        mep_data,
        output_file=f"{output_dir}/mep_3d_isosurface.png",
        show_atoms=True,
        max_points=3000  # Reduce for faster rendering
    )
    print(f"  Saved: {output_dir}/mep_3d_isosurface.png")

    # 4. Critical points (reactive sites)
    fig4 = create_mep_critical_points_plot(
        mep_data,
        output_file=f"{output_dir}/mep_critical_points.png"
    )
    print(f"  Saved: {output_dir}/mep_critical_points.png")

    plt.close('all')

    print()
    print("=" * 80)
    print("ANALYSIS COMPLETE!")
    print("=" * 80)
    print(f"Results saved to: {output_dir}/")
    print()
    print("INTERPRETATION GUIDE:")
    print("  • Negative MEP (blue):  Nucleophilic sites (electron-rich)")
    print("  • Positive MEP (red):   Electrophilic sites (electron-poor)")
    print("  • MEP minima:           Preferred sites for electrophile attack")
    print("  • MEP maxima:           Preferred sites for nucleophile attack")
    print()
    print("FOR DEGRADATION STUDIES:")
    print("  • MEP extrema indicate reactive sites")
    print("  • Nucleophilic sites (MEP < 0) attract electrophiles (e.g., H⁺, metal ions)")
    print("  • Electrophilic sites (MEP > 0) attract nucleophiles (e.g., OH⁻, H₂O)")
    print("  • Compare with Fukui functions for complete reactivity analysis")
    print("=" * 80)


def example_extract_surface_mep():
    """
    Example: Extract MEP on van der Waals surface.

    This is the most chemically relevant MEP for reactivity analysis.
    """
    print("\n" + "=" * 80)
    print("MEP ON VAN DER WAALS SURFACE")
    print("=" * 80)
    print()

    cube_file = "path/to/mep.cube"

    if not os.path.exists(cube_file):
        print(f"ERROR: File not found: {cube_file}")
        print("Please update the file path in this script.")
        return

    print(f"Parsing cube file: {cube_file}")
    mep_data = MEPParser.parse_cube_file(cube_file)

    # Extract surface MEP
    print("Extracting MEP on van der Waals surface...")
    surface_mep = MEPParser.extract_vdw_surface_mep(mep_data)
    print(f"  Extracted {len(surface_mep)} surface points")

    # Analyze surface MEP
    surface_potentials = [p[3] for p in surface_mep]
    min_surface_mep = min(surface_potentials)
    max_surface_mep = max(surface_potentials)
    mean_surface_mep = np.mean(surface_potentials)

    print()
    print("SURFACE MEP STATISTICS:")
    print("-" * 80)
    print(f"  Minimum surface MEP: {min_surface_mep:10.6f} a.u. ({min_surface_mep*27.2114:8.3f} eV)")
    print(f"  Maximum surface MEP: {max_surface_mep:10.6f} a.u. ({max_surface_mep*27.2114:8.3f} eV)")
    print(f"  Mean surface MEP:    {mean_surface_mep:10.6f} a.u. ({mean_surface_mep*27.2114:8.3f} eV)")
    print("-" * 80)
    print()

    # Find most reactive surface points
    sorted_surface = sorted(surface_mep, key=lambda p: p[3])

    print("TOP 5 NUCLEOPHILIC SURFACE SITES (most negative MEP):")
    print("-" * 80)
    print(f"{'X (Å)':<12} {'Y (Å)':<12} {'Z (Å)':<12} {'V (a.u.)':<12} {'V (eV)':<12}")
    print("-" * 80)
    for x, y, z, v in sorted_surface[:5]:
        print(f"{x:<12.4f} {y:<12.4f} {z:<12.4f} {v:<12.6f} {v*27.2114:<12.3f}")
    print()

    print("TOP 5 ELECTROPHILIC SURFACE SITES (most positive MEP):")
    print("-" * 80)
    print(f"{'X (Å)':<12} {'Y (Å)':<12} {'Z (Å)':<12} {'V (a.u.)':<12} {'V (eV)':<12}")
    print("-" * 80)
    for x, y, z, v in sorted_surface[-5:]:
        print(f"{x:<12.4f} {y:<12.4f} {z:<12.4f} {v:<12.6f} {v*27.2114:<12.3f}")
    print("-" * 80)


def example_mep_at_specific_points():
    """
    Example: Calculate MEP at specific points of interest.
    """
    print("\n" + "=" * 80)
    print("MEP AT SPECIFIC POINTS")
    print("=" * 80)
    print()

    cube_file = "path/to/mep.cube"

    if not os.path.exists(cube_file):
        print(f"ERROR: File not found: {cube_file}")
        return

    mep_data = MEPParser.parse_cube_file(cube_file)

    # Example: Calculate MEP at specific coordinates
    # (Replace these with your points of interest)
    points_of_interest = [
        ("Functional Group 1", 1.5, 2.0, 0.5),
        ("Functional Group 2", -1.0, 1.5, 1.0),
        ("Bond Center", 0.0, 0.0, 0.0)
    ]

    print("MEP AT SPECIFIC POINTS:")
    print("-" * 80)
    print(f"{'Location':<25} {'X (Å)':<10} {'Y (Å)':<10} {'Z (Å)':<10} {'V (a.u.)':<12} {'V (eV)':<10}")
    print("-" * 80)

    for label, x, y, z in points_of_interest:
        potential = MEPParser.calculate_mep_at_point(mep_data, x, y, z)
        if potential is not None:
            print(f"{label:<25} {x:<10.3f} {y:<10.3f} {z:<10.3f} "
                  f"{potential:<12.6f} {potential*27.2114:<10.3f}")
        else:
            print(f"{label:<25} {x:<10.3f} {y:<10.3f} {z:<10.3f} "
                  f"{'Out of bounds':<24}")

    print("-" * 80)


def example_combine_mep_and_fukui():
    """
    Example: Combine MEP and Fukui function analysis.

    This provides a complete picture of molecular reactivity:
    - MEP: Electrostatic interactions
    - Fukui: Frontier orbital reactivity
    """
    print("\n" + "=" * 80)
    print("COMBINED MEP + FUKUI ANALYSIS")
    print("=" * 80)
    print()

    print("For complete reactivity analysis:")
    print("  1. Run MEP analysis (this example)")
    print("  2. Run Fukui function analysis (see fukui_example.py)")
    print("  3. Compare results:")
    print()
    print("     Sites with BOTH negative MEP AND high f⁻:")
    print("       → Strong nucleophilic sites (most reactive to electrophiles)")
    print()
    print("     Sites with BOTH positive MEP AND high f⁺:")
    print("       → Strong electrophilic sites (most reactive to nucleophiles)")
    print()
    print("     Sites where MEP and Fukui disagree:")
    print("       → Check which dominates (orbital vs electrostatic control)")
    print()
    print("=" * 80)


if __name__ == "__main__":
    print("MOLECULAR ELECTROSTATIC POTENTIAL (MEP) ANALYSIS EXAMPLES")
    print("=" * 80)
    print()
    print("This script demonstrates how to parse and visualize MEP data from ORCA.")
    print()
    print("Available examples:")
    print("  1. Parse .cube file and create visualizations")
    print("  2. Extract MEP on van der Waals surface")
    print("  3. Calculate MEP at specific points")
    print("  4. Combine MEP with Fukui analysis")
    print()

    # Run example 4 (doesn't require files)
    example_combine_mep_and_fukui()

    print("\n" + "=" * 80)
    print("To run the full analysis with real ORCA files:")
    print("  1. Generate MEP cube file from ORCA (see instructions above)")
    print("  2. Update file paths in this script")
    print("  3. Uncomment the function calls below")
    print("=" * 80)

    # Uncomment to run with real files (after updating paths)
    # example_parse_cube_file()
    # example_extract_surface_mep()
    # example_mep_at_specific_points()
